export const endorsments = [
  'Administration/Leadership',
  'All Grades Art',
  'All Grades Chinese',
  'All Grades English as a Second Language',
  'All Grades French',
  'All Grades German',
  'All Grades Health and Wellness',
  'All Grades Korean',
  'All Grades Library',
  'All Grades Music',
  'All Grades Physical Education',
  'All Grades Reading',
  'All Grades School Counselor',
  'All Grades School Psychologist',
  'All Grades Spanish',
  'All Grades Theater',
  'Elementary Education',
  'Elementary Reading',
  'Middle Grades Education (4 - 8)',
  'Middle School English Language Arts',
  'Middle School Mathematics',
  'Middle School Reading',
  'Middle School Science',
  'Middle School Social Studies',
  'Secondary Agricultural Education',
  'Secondary Bible/Religious Studies',
  'Secondary Biology',
  'Secondary Business Education',
  'Secondary Chemistry',
  'Secondary Chinese',
  'Secondary Earth Science',
  'Secondary Economics',
  'Secondary English Language Arts',
  'Secondary Family and Consumer Science Education',
  'Secondary French',
  'Secondary Geography',
  'Secondary German',
  'Secondary Government',
  'Secondary History',
  'Secondary Korean',
  'Secondary Marketing Education',
  'Secondary Mathematics',
  'Secondary Physics',
  'Secondary Psychology',
  'Secondary Sociology',
  'Secondary Spanish',
  'Secondary Speech Communication',
  'Secondary Technology Engineering Education',
  'Special Education General/Comprehensive',
  'Special Education Gifted Education',
  'Special Education Interventionist',
  'Special Education Speech/Language Pathology',
];
